// ─────────────────────────────────────────────
//  ConsTradeHire — Construction Companies Directory
//  GET /api/companies          paginated list with filter
//  GET /api/companies/:slug    single company detail
// ─────────────────────────────────────────────

'use strict';
const express = require('express');
const router  = express.Router();

// ── Canadian Construction Companies Database ──
// Sources: company websites, BuildForce Canada, COCA, OGCA, CCA directories
const COMPANIES = [
  // ── NATIONAL GENERAL CONTRACTORS ──────────────────────────────────
  {
    slug: 'pcl-construction',
    name: 'PCL Construction',
    type: 'General Contractor',
    size: 'Large (5,000+)',
    hq: 'Edmonton, AB',
    provinces: ['ON','BC','AB','SK','MB','NS','QC'],
    website: 'https://www.pcl.com',
    careers: 'https://www.pcl.com/careers',
    description: 'One of Canada\'s largest general contracting organizations, operating across buildings, civil infrastructure, and industrial work.',
    trades: ['Civil','Structural Steel','Concrete','Mechanical','Electrical'],
    founded: 1906,
  },
  {
    slug: 'ellisdon',
    name: 'EllisDon Corporation',
    type: 'General Contractor',
    size: 'Large (5,000+)',
    hq: 'Mississauga, ON',
    provinces: ['ON','BC','AB','NS','QC','MB'],
    website: 'https://www.ellisdon.com',
    careers: 'https://www.ellisdon.com/careers/',
    description: 'Canadian-owned and operated construction company building some of Canada\'s most complex and iconic projects.',
    trades: ['Civil','Structural','ICI','Healthcare','Transit'],
    founded: 1951,
  },
  {
    slug: 'aecon-group',
    name: 'Aecon Group',
    type: 'General Contractor / Civil',
    size: 'Large (5,000+)',
    hq: 'Toronto, ON',
    provinces: ['ON','BC','AB','SK','NS','QC','NB'],
    website: 'https://www.aecon.com',
    careers: 'https://careers.aecon.com/',
    description: 'Publicly traded Canadian construction and infrastructure development company. Major focus on civil, nuclear, and urban transit.',
    trades: ['Civil','Pipeline','Nuclear','Transit','Utilities'],
    founded: 1877,
  },
  {
    slug: 'graham-construction',
    name: 'Graham Construction',
    type: 'General Contractor',
    size: 'Large (2,000+)',
    hq: 'Calgary, AB',
    provinces: ['ON','BC','AB','SK','MB'],
    website: 'https://www.grahamcorp.ca',
    careers: 'https://www.grahamcorp.ca/careers/',
    description: 'Employee-owned general contractor with expertise in buildings, industrial, civil, and infrastructure sectors.',
    trades: ['Civil','Industrial','Buildings','Pipelines'],
    founded: 1926,
  },
  {
    slug: 'bird-construction',
    name: 'Bird Construction',
    type: 'General Contractor',
    size: 'Large (4,000+)',
    hq: 'Mississauga, ON',
    provinces: ['ON','BC','AB','SK','MB','NS','NB','NL'],
    website: 'https://www.bird.ca',
    careers: 'https://www.bird.ca/careers/',
    description: 'Canadian publicly traded general contractor operating across ICI, industrial, civil, and maintenance sectors.',
    trades: ['ICI','Industrial','Civil','Maintenance'],
    founded: 1920,
  },
  {
    slug: 'ledcor',
    name: 'Ledcor Group',
    type: 'General Contractor',
    size: 'Large (7,000+)',
    hq: 'Vancouver, BC',
    provinces: ['ON','BC','AB','SK','MB','YT','NT'],
    website: 'https://www.ledcor.com',
    careers: 'https://www.ledcor.com/careers',
    description: 'Diversified Canadian construction company with divisions in building, civil, industrial, pipeline, and telecommunications.',
    trades: ['Civil','Pipeline','Buildings','Telecommunications','Industrial'],
    founded: 1947,
  },
  {
    slug: 'pomerleau',
    name: 'Pomerleau',
    type: 'General Contractor',
    size: 'Large (2,500+)',
    hq: 'Saint-Georges, QC',
    provinces: ['ON','BC','AB','QC','NS','NB'],
    website: 'https://www.pomerleau.ca',
    careers: 'https://www.pomerleau.ca/en/careers/',
    description: 'One of Canada\'s most innovative construction companies, active in commercial, institutional, civil, and residential sectors.',
    trades: ['Commercial','Institutional','Civil','Residential'],
    founded: 1960,
  },
  {
    slug: 'chandos-construction',
    name: 'Chandos Construction',
    type: 'General Contractor',
    size: 'Medium (1,000+)',
    hq: 'Edmonton, AB',
    provinces: ['ON','AB','BC'],
    website: 'https://chandos.com',
    careers: 'https://chandos.com/careers/',
    description: 'Employee-owned B Corp certified general contractor with a focus on sustainable construction and innovative project delivery.',
    trades: ['Commercial','Industrial','Institutional'],
    founded: 1980,
  },

  // ── ONTARIO GENERAL CONTRACTORS ───────────────────────────────────
  {
    slug: 'bondfield-construction',
    name: 'Bondfield Construction',
    type: 'General Contractor',
    size: 'Medium (500+)',
    hq: 'Concord, ON',
    provinces: ['ON'],
    website: 'https://www.bondfield.com',
    careers: 'https://www.bondfield.com/careers/',
    description: 'Ontario-based general contractor specializing in healthcare, education, and infrastructure projects.',
    trades: ['ICI','Healthcare','Education','Institutional'],
    founded: 1987,
  },
  {
    slug: 'buttcon',
    name: 'Buttcon Limited',
    type: 'General Contractor',
    size: 'Medium (200+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://www.buttcon.com',
    careers: 'https://www.buttcon.com/careers/',
    description: 'Toronto-based general contractor with deep expertise in ICI and institutional construction across Ontario.',
    trades: ['ICI','Institutional','Commercial'],
    founded: 1946,
  },
  {
    slug: 'eastern-construction',
    name: 'Eastern Construction',
    type: 'General Contractor',
    size: 'Medium (300+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://www.easternconstruction.com',
    careers: 'https://www.easternconstruction.com/careers/',
    description: 'Toronto general contractor with a strong track record in healthcare, institutional, commercial, and industrial sectors.',
    trades: ['Healthcare','Institutional','Commercial','Industrial'],
    founded: 1952,
  },
  {
    slug: 'taggart-group',
    name: 'Taggart Group of Companies',
    type: 'General Contractor / Civil',
    size: 'Medium (400+)',
    hq: 'Ottawa, ON',
    provinces: ['ON','QC'],
    website: 'https://www.taggartgroup.com',
    careers: 'https://www.taggartgroup.com/careers/',
    description: 'Ottawa-based construction and real estate group active in general contracting, civil construction, and land development.',
    trades: ['Civil','Buildings','Sitework','Asphalt'],
    founded: 1948,
  },
  {
    slug: 'maple-reinders',
    name: 'Maple Reinders',
    type: 'General Contractor',
    size: 'Medium (300+)',
    hq: 'Mississauga, ON',
    provinces: ['ON','AB','BC'],
    website: 'https://www.maplereinders.com',
    careers: 'https://www.maplereinders.com/careers/',
    description: 'Employee-owned contractor specializing in industrial, process, and infrastructure projects including water, waste, and energy facilities.',
    trades: ['Water/Wastewater','Industrial','Process','Civil'],
    founded: 1972,
  },
  {
    slug: 'kenaidan-contracting',
    name: 'Kenaidan Contracting',
    type: 'General Contractor',
    size: 'Medium (200+)',
    hq: 'Mississauga, ON',
    provinces: ['ON'],
    website: 'https://www.kenaidan.com',
    careers: 'https://www.kenaidan.com/careers/',
    description: 'Ontario-based contractor known for complex structural and civil work including tunnels, transit, and heavy infrastructure.',
    trades: ['Civil','Structural','Underground','Transit'],
    founded: 1954,
  },
  {
    slug: 'vanbots-construction',
    name: 'Vanbots Construction',
    type: 'General Contractor',
    size: 'Medium (200+)',
    hq: 'Concord, ON',
    provinces: ['ON'],
    website: 'https://www.vanbots.com',
    careers: 'https://www.vanbots.com/careers',
    description: 'Ontario general contractor specializing in commercial, industrial, and institutional buildings.',
    trades: ['Commercial','Industrial','Institutional'],
    founded: 1962,
  },
  {
    slug: 'm-sullivan-son',
    name: 'M. Sullivan & Son Limited',
    type: 'General Contractor',
    size: 'Medium (200+)',
    hq: 'Arnprior, ON',
    provinces: ['ON','QC'],
    website: 'https://www.msullivan.ca',
    careers: 'https://www.msullivan.ca/careers/',
    description: 'Eastern Ontario general contractor with expertise in institutional, commercial, and civil construction.',
    trades: ['Institutional','Commercial','Civil'],
    founded: 1906,
  },
  {
    slug: 'clark-construction',
    name: 'Clark Construction Group',
    type: 'General Contractor',
    size: 'Small (100+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://www.clarkconstruction.ca',
    careers: 'https://www.clarkconstruction.ca/careers/',
    description: 'Mid-size Toronto contractor focused on commercial interiors, building restoration, and institutional fit-outs.',
    trades: ['Commercial','Interiors','Restoration'],
    founded: 1988,
  },
  {
    slug: 'dalton',
    name: 'Dalton Construction',
    type: 'General Contractor',
    size: 'Small (50+)',
    hq: 'Hamilton, ON',
    provinces: ['ON'],
    website: 'https://www.daltonconstruction.ca',
    careers: 'https://www.daltonconstruction.ca/careers/',
    description: 'Hamilton-area general contractor serving commercial, institutional, and light industrial clients.',
    trades: ['Commercial','Institutional','Industrial'],
    founded: 2001,
  },
  {
    slug: 'norlon-builders',
    name: 'Norlon Builders London',
    type: 'General Contractor',
    size: 'Small (50+)',
    hq: 'London, ON',
    provinces: ['ON'],
    website: 'https://www.norlon.ca',
    careers: 'https://www.norlon.ca/careers',
    description: 'Southwest Ontario general contractor specializing in residential and light commercial projects.',
    trades: ['Residential','Commercial'],
    founded: 1993,
  },

  // ── INTERNATIONAL CONTRACTORS WITH CANADA PRESENCE ────────────────
  {
    slug: 'skanska-canada',
    name: 'Skanska Canada',
    type: 'General Contractor',
    size: 'Large (2,000+)',
    hq: 'Toronto, ON',
    provinces: ['ON','BC','AB','QC'],
    website: 'https://www.skanska.com/en/markets/canada/',
    careers: 'https://www.skanska.com/en/careers/',
    description: 'Canadian arm of global construction giant Skanska. Specializes in transit, healthcare, and complex ICI projects.',
    trades: ['Transit','Healthcare','ICI','Civil'],
    founded: 1897,
  },
  {
    slug: 'turner-construction-canada',
    name: 'Turner Construction Canada',
    type: 'General Contractor',
    size: 'Large (1,000+)',
    hq: 'Toronto, ON',
    provinces: ['ON','BC'],
    website: 'https://www.turnerconstruction.com/markets/canada',
    careers: 'https://careers.turnerconstruction.com/',
    description: 'One of the world\'s largest construction companies. Canadian operations focused on high-rise, healthcare, and data centers.',
    trades: ['High-Rise','Healthcare','Data Centers','Commercial'],
    founded: 1902,
  },
  {
    slug: 'aecom-construction',
    name: 'AECOM',
    type: 'Engineering / Construction Management',
    size: 'Large (5,000+ in Canada)',
    hq: 'Toronto, ON',
    provinces: ['ON','BC','AB','QC','NS','MB'],
    website: 'https://aecom.com',
    careers: 'https://aecom.com/careers/',
    description: 'Global infrastructure firm delivering design, engineering, construction, and project management services.',
    trades: ['Civil','Structural','Environmental','Transportation'],
    founded: 1990,
  },
  {
    slug: 'stantec',
    name: 'Stantec',
    type: 'Engineering / Construction Management',
    size: 'Large (7,000+ in Canada)',
    hq: 'Edmonton, AB',
    provinces: ['ON','BC','AB','SK','MB','QC','NS','NB','NL'],
    website: 'https://www.stantec.com',
    careers: 'https://www.stantec.com/en/careers',
    description: 'Canadian-founded global design and engineering firm. Construction management, inspection, and project delivery services.',
    trades: ['Civil','Environmental','Water','Transportation'],
    founded: 1954,
  },

  // ── RESIDENTIAL BUILDERS ──────────────────────────────────────────
  {
    slug: 'mattamy-homes',
    name: 'Mattamy Homes',
    type: 'Residential Builder',
    size: 'Large (3,000+)',
    hq: 'Toronto, ON',
    provinces: ['ON','AB','BC'],
    website: 'https://www.mattamyhomes.com',
    careers: 'https://www.mattamyhomes.com/careers/',
    description: 'Canada\'s largest privately owned residential homebuilder. Builds single-family and multi-family communities across Ontario and Alberta.',
    trades: ['Framing','Concrete','Electrical','Plumbing','HVAC','Finishing'],
    founded: 1978,
  },
  {
    slug: 'great-gulf-homes',
    name: 'Great Gulf Homes',
    type: 'Residential Builder',
    size: 'Medium (1,000+)',
    hq: 'Toronto, ON',
    provinces: ['ON','AB'],
    website: 'https://www.greatgulf.com',
    careers: 'https://www.greatgulf.com/careers/',
    description: 'Leading Toronto-area homebuilder constructing low-rise, mid-rise, and high-rise communities.',
    trades: ['Concrete','Framing','Finishing','Mechanical','Electrical'],
    founded: 1975,
  },
  {
    slug: 'menkes-developments',
    name: 'Menkes Developments',
    type: 'Residential / Commercial Developer',
    size: 'Medium (500+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://www.menkes.com',
    careers: 'https://www.menkes.com/about/careers/',
    description: 'Toronto developer and builder of high-rise condominiums, office towers, and commercial projects.',
    trades: ['Concrete','High-Rise','Commercial','Mechanical','Electrical'],
    founded: 1954,
  },
  {
    slug: 'tribute-communities',
    name: 'Tribute Communities',
    type: 'Residential Builder',
    size: 'Medium (200+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://tributecommunities.com',
    careers: 'https://tributecommunities.com/careers/',
    description: 'Award-winning Ontario homebuilder specializing in low-rise communities and condominiums across the GTA.',
    trades: ['Framing','Finishing','Mechanical','Electrical'],
    founded: 1982,
  },

  // ── MECHANICAL / ELECTRICAL / SPECIALTY ──────────────────────────
  {
    slug: 'ainsworth',
    name: 'Ainsworth Inc.',
    type: 'Mechanical / Electrical Contractor',
    size: 'Large (3,000+)',
    hq: 'Mississauga, ON',
    provinces: ['ON','BC','AB','SK','MB','QC'],
    website: 'https://www.ainsworth.ca',
    careers: 'https://www.ainsworth.ca/careers/',
    description: 'Canada\'s largest single-source mechanical, electrical, and technical services contractor. Serving ICI, healthcare, and data centres.',
    trades: ['HVAC','Plumbing','Electrical','Controls','BAS'],
    founded: 1961,
  },
  {
    slug: 'johnson-controls-canada',
    name: 'Johnson Controls Canada',
    type: 'Mechanical / BAS Contractor',
    size: 'Large (2,000+ in Canada)',
    hq: 'Mississauga, ON',
    provinces: ['ON','BC','AB','QC'],
    website: 'https://www.johnsoncontrols.com',
    careers: 'https://jobs.johnsoncontrols.com/',
    description: 'Global building technology leader. Canadian operations install and maintain HVAC, fire, security, and building automation systems.',
    trades: ['HVAC','Fire','Security','BAS','Controls'],
    founded: 1885,
  },
  {
    slug: 'williams-mechanical',
    name: 'Williams Mechanical',
    type: 'Mechanical Contractor',
    size: 'Medium (200+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://www.williamsmechanical.ca',
    careers: 'https://www.williamsmechanical.ca/careers/',
    description: 'Ontario mechanical contractor specializing in plumbing, HVAC, and hydronic systems for ICI projects.',
    trades: ['Plumbing','HVAC','Hydronic','Piping'],
    founded: 1965,
  },
  {
    slug: 'pivot-electric',
    name: 'Pivot Electric',
    type: 'Electrical Contractor',
    size: 'Medium (200+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://www.pivotelectric.ca',
    careers: 'https://www.pivotelectric.ca/careers/',
    description: 'Toronto-area electrical contractor serving ICI and residential sectors, specializing in tenant improvements and base building work.',
    trades: ['Electrical','Lighting','Power Distribution'],
    founded: 2000,
  },
  {
    slug: 'the-mitchell-group',
    name: 'The Mitchell Group',
    type: 'Electrical Contractor',
    size: 'Small (100+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://mitchellelectric.ca',
    careers: 'https://mitchellelectric.ca/careers/',
    description: 'Ontario electrical contractor for commercial, industrial, and institutional projects.',
    trades: ['Electrical','Low Voltage','Data'],
    founded: 1967,
  },
  {
    slug: 'garland-canada',
    name: 'Garland Canada',
    type: 'Roofing / Waterproofing',
    size: 'Medium (100+)',
    hq: 'Mississauga, ON',
    provinces: ['ON','QC','AB','BC'],
    website: 'https://www.garlandcanada.ca',
    careers: 'https://www.garlandcanada.ca/careers/',
    description: 'Canadian leader in roofing systems and waterproofing solutions for commercial and institutional buildings.',
    trades: ['Roofing','Waterproofing','Sheet Metal'],
    founded: 1976,
  },

  // ── CIVIL / INFRASTRUCTURE ────────────────────────────────────────
  {
    slug: 'miller-group',
    name: 'Miller Group',
    type: 'Civil Contractor',
    size: 'Large (5,000+)',
    hq: 'Markham, ON',
    provinces: ['ON','QC'],
    website: 'https://www.millergroup.ca',
    careers: 'https://www.millergroup.ca/careers/',
    description: 'Ontario\'s largest highway and municipal contractor. Part of Colas Group. Asphalt, aggregates, road construction, and maintenance.',
    trades: ['Asphalt','Road Building','Civil','Aggregates','Paving'],
    founded: 1917,
  },
  {
    slug: 'r-v-anderson',
    name: 'R.V. Anderson Associates',
    type: 'Engineering / Construction Management',
    size: 'Medium (200+)',
    hq: 'Toronto, ON',
    provinces: ['ON','AB'],
    website: 'https://www.rvanderson.com',
    careers: 'https://www.rvanderson.com/careers/',
    description: 'Canadian engineering firm specializing in water, wastewater, and municipal infrastructure design and construction management.',
    trades: ['Civil','Water','Wastewater','Municipal'],
    founded: 1949,
  },
  {
    slug: 'priestly-demolition',
    name: 'Priestly Demolition',
    type: 'Demolition Contractor',
    size: 'Medium (200+)',
    hq: 'King City, ON',
    provinces: ['ON','QC','AB'],
    website: 'https://www.priestlydemolition.com',
    careers: 'https://www.priestlydemolition.com/careers/',
    description: 'One of North America\'s largest demolition contractors. Specializes in industrial, commercial, and infrastructure deconstruction.',
    trades: ['Demolition','Excavation','Hazmat','Site Prep'],
    founded: 1981,
  },
  {
    slug: 'smith-brothers-wilson',
    name: 'Smith Brothers & Wilson',
    type: 'Civil Contractor',
    size: 'Medium (150+)',
    hq: 'Woodstock, ON',
    provinces: ['ON'],
    website: 'https://www.sbw.ca',
    careers: 'https://www.sbw.ca/careers/',
    description: 'Southwestern Ontario civil contractor specializing in underground infrastructure, sewer, water main, and road works.',
    trades: ['Underground','Sewers','Water Main','Road Building'],
    founded: 1908,
  },
  {
    slug: 'coco-paving',
    name: 'Coco Paving',
    type: 'Civil / Asphalt',
    size: 'Medium (300+)',
    hq: 'Ottawa, ON',
    provinces: ['ON','QC'],
    website: 'https://www.cocopaving.com',
    careers: 'https://www.cocopaving.com/careers/',
    description: 'Eastern Ontario civil contractor specializing in asphalt paving, road construction, and aggregates.',
    trades: ['Asphalt','Paving','Civil','Aggregates'],
    founded: 1960,
  },
  {
    slug: 'lafarge-canada',
    name: 'Lafarge Canada',
    type: 'Construction Materials',
    size: 'Large (5,000+)',
    hq: 'Calgary, AB',
    provinces: ['ON','BC','AB','QC','MB','SK','NS'],
    website: 'https://www.lafarge.ca',
    careers: 'https://www.lafarge.ca/en/careers',
    description: 'Part of Holcim Group. Produces cement, aggregates, ready-mix concrete, and asphalt for Canadian construction.',
    trades: ['Ready-Mix','Concrete','Masonry','Aggregates'],
    founded: 1956,
  },

  // ── SPECIALTY / RESTORATION ───────────────────────────────────────
  {
    slug: 'restorecore',
    name: 'RestoreCore',
    type: 'Restoration Contractor',
    size: 'Medium (200+)',
    hq: 'Hamilton, ON',
    provinces: ['ON'],
    website: 'https://www.restorecore.com',
    careers: 'https://www.restorecore.com/careers/',
    description: 'Ontario restoration contractor specializing in building envelope, masonry, concrete repair, and exterior restoration.',
    trades: ['Masonry','Concrete Repair','Caulking','Building Envelope'],
    founded: 1995,
  },
  {
    slug: 'crs-contractors-restoration',
    name: 'CRS — Contractors Restoration Services',
    type: 'Restoration Contractor',
    size: 'Small (100+)',
    hq: 'Brampton, ON',
    provinces: ['ON'],
    website: 'https://www.crs.ca',
    careers: 'https://www.crs.ca/careers/',
    description: 'Ontario-based restoration contractor for water, fire, and mold remediation in commercial and residential properties.',
    trades: ['Restoration','Remediation','Drywall','Flooring'],
    founded: 1974,
  },
  {
    slug: 'forma-steel',
    name: 'Forma-Steel',
    type: 'Structural Steel',
    size: 'Medium (100+)',
    hq: 'Hamilton, ON',
    provinces: ['ON'],
    website: 'https://www.forma-steel.com',
    careers: 'https://www.forma-steel.com/careers/',
    description: 'Hamilton-area steel erector and fabricator serving commercial, industrial, and institutional markets.',
    trades: ['Structural Steel','Ironwork','Welding'],
    founded: 1982,
  },
  {
    slug: 'dufferin-concrete',
    name: 'Dufferin Concrete',
    type: 'Concrete / Ready-Mix',
    size: 'Large (500+)',
    hq: 'Toronto, ON',
    provinces: ['ON'],
    website: 'https://www.dufferinconcrete.com',
    careers: 'https://www.dufferinconcrete.com/careers/',
    description: 'Ontario\'s leading ready-mix concrete supplier. Part of CRH Canada. Operates across the GTA and Ontario.',
    trades: ['Ready-Mix','Concrete Pumping','Aggregate'],
    founded: 1912,
  },
  {
    slug: 'surespan',
    name: 'Surespan Construction',
    type: 'Civil / Bridges',
    size: 'Medium (200+)',
    hq: 'Toronto, ON',
    provinces: ['ON','QC'],
    website: 'https://www.surespan.ca',
    careers: 'https://www.surespan.ca/careers/',
    description: 'Specialist in bridge construction, rehabilitation, and structural repair across Ontario and Quebec.',
    trades: ['Bridges','Structural','Concrete','Civil'],
    founded: 1957,
  },
  {
    slug: 'hardrock-construction',
    name: 'Hard Rock Mining & Tunnelling',
    type: 'Underground / Tunnelling',
    size: 'Medium (300+)',
    hq: 'Sudbury, ON',
    provinces: ['ON','QC','MB'],
    website: 'https://www.hardrockconstruction.com',
    careers: 'https://www.hardrockconstruction.com/careers/',
    description: 'Northern Ontario tunnelling and underground construction specialist. Active in mining infrastructure, transit tunnels, and shafts.',
    trades: ['Tunnelling','Underground Mining','Shaft Sinking','Blasting'],
    founded: 1973,
  },
];

// ─── GET /api/companies ───────────────────────
router.get('/', (req, res) => {
  const { type = '', province = '', search = '', page = 1 } = req.query;
  const take = 20;
  const skip = (Number(page) - 1) * take;

  let list = COMPANIES;

  if (type)     list = list.filter(c => c.type.toLowerCase().includes(type.toLowerCase()));
  if (province) list = list.filter(c => c.provinces.includes(province.toUpperCase()));
  if (search) {
    const q = search.toLowerCase();
    list = list.filter(c =>
      c.name.toLowerCase().includes(q) ||
      c.type.toLowerCase().includes(q) ||
      c.hq.toLowerCase().includes(q) ||
      (c.trades || []).some(t => t.toLowerCase().includes(q))
    );
  }

  const total = list.length;
  const page_data = list.slice(skip, skip + take);

  // Unique types for filter UI
  const types = [...new Set(COMPANIES.map(c => c.type))].sort();

  res.json({
    companies: page_data,
    total,
    pages: Math.ceil(total / take),
    types
  });
});

// ─── GET /api/companies/:slug ─────────────────
router.get('/:slug', (req, res) => {
  const company = COMPANIES.find(c => c.slug === req.params.slug);
  if (!company) return res.status(404).json({ error: 'Company not found' });
  res.json({ company });
});

module.exports = router;
